name: Lint

# Version: 2.0.1
# Modified: Yes
#

# GitHub repo configuration:
# 1. If you have protected branches, go to Branches > edit protected branch > enable 'Require status checks to pass before
#    merging' and select the 'ESLint' status check.

# Note: make sure to commit package-lock.json, this is needed for `npm ci`.

# Defines the trigger for this action (e.g. [pull_request, push])
# For more information see: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#about-workflow-events)
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      # Lint
      - run: |
          npm ci --ignore-scripts --audit=false
          npm run lint

